name: workmanager
description: Flutter Workmanager. This plugin allows you to schedule background work on Android and iOS.
version: 0.5.1+breez
homepage: https://github.com/fluttercommunity/flutter_workmanager
repository: https://github.com/fluttercommunity/flutter_workmanager
issue_tracker: https://github.com/fluttercommunity/flutter_workmanager/issues

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: <2.4.0 # Requires Flutter 3.10
  flutter_lints: ^2.0.1
  mockito: ^5.4.0
  test: ^1.22.0

flutter:
  plugin:
    platforms:
      android:
        package: be.tramckrijte.workmanager
        pluginClass: WorkmanagerPlugin
      ios:
        pluginClass: WorkmanagerPlugin
